# Generated by Django 5.0.7 on 2024-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_address_alter_identity_primary_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='primary_address',
        ),
        migrations.AddField(
            model_name='identity',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identity',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identity',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='identity',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identity',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
