# Generated by Django 5.0.7 on 2024-07-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_remove_identity_primary_address_identity_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
